### ISSUE TITLE
tree-shaking

### ISSUE THREAD

**Issue by godu** [floydspace/effect-aws#28]
I was surprise that a simple program produces a ~500kb bundle

```ts
import {Effect} from 'effect';
import {DynamoDBService} from '@effect-aws/client-dynamodb';

const {listTables} = Effect.serviceFunctions(DynamoDBService);

export const program = listTables({});

```

bundled with 
```shell
esbuild ./src/index.ts --bundle "--external:@aws-sdk/*" --outfile=./dist/index.js --metafile=./dist/meta.json
```

Maybe we should improve the tree-shacking readiness.

**Comment by godu** [comment]
Perhaps we could disable the `"sideEffects"` property in the `package.json` (cf https://webpack.js.org/guides/tree-shaking/).

**Comment by floydspace** [comment]
oh, wow, didn't know about this property, I tried me end project and indeed reduced size in like twice.
however when I tried to add it in the @effect-aws packages, I didn't see any improvements
is it supposed to be used in libs?

**Comment by floydspace** [comment]
> I was surprise that a simple program produces a ~500kb bundle

<img width="743" alt="image" src="https://github.com/floydspace/effect-aws/assets/5180700/5d1636e4-7dec-4781-86b7-9363dcb9dcbc">
 I cannot reproduce it
I'm using command

```sh
esbuild --bundle src/lambda.ts --target=\"node18\" --platform=\"node\" --outfile=\"dist/index.js\" --tsconfig=\"tsconfig.json\" --tree-shaking=true --main-fields=module,main --minify --metafile=dist/meta.json
```

**Comment by godu** [comment]
Oh, I don't reproduce it any more...
But I think it will be more safe to add "sideEffects: [] like effect does (cf: https://discord.com/channels/795981131316985866/1174418279276757002/1174680724377440356).
You can close the issue if you want :ok:

**Comment by godu** [comment]
Ok, I have a hint. In my sample, I don't use the `DefaultDynamoDBServiceLayer` and esbuild should be able to prune the `../../node_modules/@effect-aws/client-dynamodb/lib/esm/DynamoDBService.js` file.

Without the `sideEffects` property, the `DynamoDBService` module is present in my bundle, even if I use any your recommended flags.

I think it will be more safe to add `"sideEffects: []` like effect does (cf: https://discord.com/channels/795981131316985866/1174418279276757002/1174680724377440356).

**Comment by floydspace** [comment]
agreed. If you feel like you can raise a PR, or I will pick it up in the evening.
