### ISSUE TITLE
[Feature Request] AWS CodeDeploy

### ISSUE THREAD

**Issue by leggomuhgreggo** [floydspace/effect-aws#52]
If you're still taking requests, [@aws-sdk/client-codedeploy](https://www.npmjs.com/package/@aws-sdk/client-codedeploy) might be another worthy addition.

In particular, I think codedeploy implementations tend to involve polling and multiple error cases, and would serve as a compelling exhibition of those complementary features in Effect.

Incidentally, very cool repo! 🏆

**Comment by floydspace** [comment]
Hey Greg, I'm glad you find the repo useful.
yes you can go ahead with adding a new client
here is instruction how to generate it using codegen: https://github.com/floydspace/effect-aws/pull/38

**Comment by floydspace** [comment]
the codedeploy client has been released [@effect-aws/client-codedeploy@1.0.0](https://github.com/floydspace/effect-aws/releases/tag/%40effect-aws%2Fclient-codedeploy%401.0.0)
