### ISSUE TITLE
Secrets Manager `ConfigProvider`?

### ISSUE THREAD

**Issue by dudeofawesome** [floydspace/effect-aws#55]
Would there be interest in implementing a `ConfigProvider` with Secrets Manager as a backend?

Things like Lambdas could really benefit from this, enabling secure retrieval of config secrets like a DB URI.

**Comment by dudeofawesome** [comment]
Hmm, I was kinda thinking it would live in the same package as the client (although, I'm not sure how that would work with codegen?) 
If you wanted to use a separate package, I also think have "provider" in the name makes sense, although I'd suggest either pluralizing it ("config-providers") since there's potential for more than one, or putting "secrets-manager" in the name as well.

**Comment by floydspace** [comment]
Hey @dudeofawesome 

I decided to use `@effect-aws/secrets-manager` name (similar to `@effect-aws/lambda` and `@effect-aws/client-lambda` naming pair), so it incapsulates all possible utilities for secrets manager

the [v1.0.0](https://github.com/floydspace/effect-aws/blob/main/packages/secrets-manager/CHANGELOG.md) is released

**Comment by dudeofawesome** [comment]
It looks like there's a bug regarding default values. 

If I specify a secret that doesn't exist, with a default value to fall back to, I would expect it to search for the secret, not find it, and allow the default value to be used instead.

Instead, I'm seeing an error being thrown when the secret isn't found.

Here's a repro of the issue: https://effect.website/play#3b7f6e22fc22
You can switch out the provided config provider with the other sample ones to see the expected behavior.

I actually ran in to this issue myself when I was working on my own implementation of this provider. You can see some discussion of it [in the Discord here](https://discord.com/channels/795981131316985866/1276661894349979648/1277852456931561484).

**Comment by floydspace** [comment]
@dudeofawesome thanks for the feedback, I will write some additional tests cases. I think it makes sense allow default values only on MissingData error. 

Is your implementation somehow looks like mine?

**Comment by dudeofawesome** [comment]
Yeah, my implementation and yours look pretty similar, although mine was more of a quick prototype. I'd meant to make it into a PR, but you beat me to it haha.

I'm a bit of a noob with Effect, so I'd be curious to hear more of your thoughts about the default / `ConfigError` interaction. To me, with both of us having separately made the same assumption that all types of `ConfigError` allowing for default fallback, it seems like the current behavior maybe needs to be looked at. It just seems odd to effectively have to lie about the type of error that was raised.
