### ISSUE TITLE
[Question] Instance Pool of S3Client

### ISSUE THREAD

**Issue by Zamion101** [floydspace/effect-aws#57]
Is there a way to create a Instance Pool like create 10 Instances of extended S3Client and when it's needed take 1 from Pool use it and release back to Pool to be used from somewhere else. Also when Pool is empty wait for one to be available?

I read the client-s3 source code but it does look like one instance is beign created and used everywhere.

**Comment by floydspace** [comment]
indeed it creates a single instance which can be provided on the very edge and reused everywhere.

I'm trying to understand what is the reason you need a pool of instances?

probably it is possible to do using effect's [Pool](https://effect-ts.github.io/effect/effect/Pool.ts.html) data structure

**Comment by Zamion101** [comment]
Thank you for your answer. My original idea was to have multiple client to upload files concurrently but after some test I found out that one client is more than capable of uploading multiple files using `flatMap(f, {concurrency: x})`.
