### ISSUE TITLE
Upgrade powertools to V2

### ISSUE THREAD

**Issue by mathiasmaerker** [floydspace/effect-aws#62]
Hey, 
I just got the message tat powertools v1 is deprecated. Do you have plans (and maybe need support) to implement v2?

**Comment by floydspace** [comment]
Hey @mathiasmaerker, thank you for raising this issue.
I already implemented this as part of [this commit](https://github.com/floydspace/effect-aws/commit/55ab70f83ac2cf07daea09ee5dfa28e3f6452d42)
and personally use with powertools v2.7.0

**Comment by mathiasmaerker** [comment]
Hmm, are you sure? I am on `1.3.0`, deleted node_modules and reinstalled via `pnpm i` and when  I check my node_modules I see:
![image](https://github.com/user-attachments/assets/52553431-3c92-450b-98de-232bdf01ae04)

**Comment by floydspace** [comment]
hey @mathiasmaerker 

it is becasue the `@aws-lambda-powertools/logger` is peer dependency of `@effect-aws/powertools-logger`, what you need is include the `@aws-lambda-powertools/logger@^2` in your package.json as dependency.
Apparently pnpm installs the peer dependency for you if you do not include it, and apparently it installs the closest matching one which is 1.9.0 as stated in dev dependency of the package

I should mention in readme though, good point

**Comment by floydspace** [comment]
@mathiasmaerker looks like you were right.
it supported v2, but till version 2.7.0, now it is fixed
