### ISSUE TITLE
SSM Config Provider - decrypted values

### ISSUE THREAD

**Issue by florianbepunkt** [floydspace/effect-aws#63]
From the code it seems that you can't get decrypted values from SSM. https://github.com/floydspace/effect-aws/blob/7088fc42e744e9767be654e3165bd0eda2d20eb0/packages/ssm/src/ConfigProvider.ts#L44

As far as I know you can add the option `WithDecryption: true ` without affecting unencrypted parameters.

**Comment by floydspace** [comment]
Hey @florianbepunkt , thanks for raising it.
it is a good point, looks like we can populate this flag for [Config.redacted](https://effect.website/docs/guides/configuration#redacted) properties. there is no other ways to provide config metadata
